### PR TITLE
Upgrade to 1.24.1

### PR DESCRIPTION
**Pull request by npadmana**
Upgrade the testing to Chapel 1.24.1

### CODE REVIEW

**Comment by npadmana** [comment]
@ronawho -- Just decided to remove 1.20 and add in 1.24.1 (and kept 1.22). Also, it looks like Travis is no longer free (I just signed up for the free plan which gives me about a year). Did Chapel switch to github actions? Do you know how to easily migrate?

PS Not much to review here! :-)

**Comment by ronawho** [comment]
Yeah, we switched a while back. I had a prototype in https://github.com/ronawho/DistributedFFT/pull/2 that switched to github actions. I can update that and PR it if you want.

**Review by ronawho — APPROVED** [review]

**Comment by ronawho** [comment]
https://github.com/npadmana/DistributedFFT/pull/76 if you want to go with github actions.

**Comment by npadmana** [comment]
Closing this in favor of github actions #76 thanks to @ronawho .

**Pull request closed without merging**
